sudo: true
merge_mode: replace   # for custom builds
matrix:
  include:
    - os: linux
      dist: bionic
      name: bionic linux, python3.6

before_install:
  - sudo apt-get update
  - sudo apt-get install -y gcc g++ pkg-config python3-minimal libboost-all-dev libssl-dev libsqlite3-dev cmake build-essential bison byacc flex libgmp3-dev libfl-dev
  
  - wget https://github.com/yufengzh/NAC-ABE/releases/download/v1.0/libopenabe-1.0.0-linux.tar.gz
  - tar xzvf libopenabe-1.0.0-linux.tar.gz
  - cd libopenabe-1.0.0-linux/
  - . ./env
  - make && sudo make install
  - sudo ldconfig
  - cd ..

  - git clone https://github.com/named-data/ndn-cxx
  - cd ndn-cxx/
  - git checkout ndn-cxx-0.7.0
  - ./waf configure && ./waf && sudo ./waf install && cd ..
install:
  - ./waf configure --with-tests
  - ./waf
  - sudo ./waf install
  - sudo ldconfig
script:
  - cd ./build
  - ./unit-tests